cache:
  untracked: true
build:
  stage: build
  script: "mvn install -B -DskipTests"
  artifacts:
    paths: 
    - target/*.jar
test:
  script: "mvn test -B"
integration-test:
  script: "mvn failsafe:integration-test failsafe:verify -B"
deploy:
  stage: deploy
  script:
    - scp target/*.jar obp-05.esl.saic.com:~/deployments/${CI_PROJECT_NAME}.jar
    - ssh -tt obp-05.esl.saic.com "sudo systemctl restart ${CI_PROJECT_NAME}"
  environment:
    name: test
  only:
  - master

deploy_demo:
  stage: deploy
  script:
    - "docker build -t obp-03.esl.saic.com:5000/neo4j-service ."
    - "docker push obp-03.esl.saic.com:5000/neo4j-service"
    - "ssh obp-03.esl.saic.com 'docker-compose pull neo4j-service'"
    - "ssh obp-03.esl.saic.com 'docker-compose up -d neo4j-service'"
  environment:
    name: test
  when: manual
  only:
    - master