cache:
  untracked: true
build:
  stage: build
  script: "mvn install -B -DskipTests"
  artifacts:
    paths: 
    - target/*.jar
test:
  script: "mvn test -B"
integration-test:
  script: "mvn failsafe:integration-test failsafe:verify -B"
deploy:
  stage: deploy
  script:
    - pwd
    - echo "${CI_PROJECT_NAME}"
    - scp target/restservice-1.0.jar obp-05.esl.saic.com:deployments/${CI_PROJECT_NAME}.jar
    - ssh -t -t obp-05.esl.saic.com "sudo systemctl restart ${CI_PROJECT_NAME}"
  environment:
    name: test
  only:
  - master

deploy_demo:
  stage: deploy
  script:
    - "docker build -t obp-03.esl.saic.com:5000/restservice ."
    - "docker push obp-03.esl.saic.com:5000/restservice"
    - "ssh obp-03.esl.saic.com 'docker-compose pull restservice'"
    - "ssh obp-03.esl.saic.com 'docker-compose up -d restservice'"
  environment:
    name: test
  when: manual
  only:
  - master